library(datasets)
print(rivers)
length(rivers)
mean(rivers)
median(rivers)
sd(rivers)
var(rivers)
min(rivers)
max(rivers)
library(psych)
psych::describe(rivers)
rivers.Des.1 <- c(mean(rivers),median(rivers),sd(rivers),var(rivers),max(rivers),min(rivers))
des <- describe((rivers))
feature_name <- names(des)
value <- c(des$vars,des$n,des$mean,des$sd,des$median,des$trimmed,des$mad,des$min,des$max,des$range,des$skew,des$kurtosis,des$se)
#value <- c(1,121,591.18,493.87,425,490.95,214.98,135,3710,3575,3.15,13.07,41.59)
rivers.Des.2 <- data.frame(feature_name,value)
rivers.Des.2
print(nrow(women))
print(ncol(women))
print(head(women))
print(tail(women))
mean(women$height)
var(women$height)
women.Height60 <- subset(women,height >60)
print(women.Height60)
women.list <- list(women$height,women$weight)
print(women.list)
women.matrix <- as.matrix(women)
print(women.matrix)
print(t(women.matrix))
cor(women$height,women$weight)
